## This file should be loaded under <robot description>_collision

default_collision_operations:
  - object1: platform
    object2: arm
    operation: enable
    
  - object1: torso
    object2: arm
    operation: enable
    
  - object1: tablet
    object2: arm
    operation: enable
    
  - object1: base_link
    object2: arm_0_link
    operation: disable    
    
  - object1: platform
    object2: hand
    operation: enable
    
  - object1: torso
    object2: hand
    operation: enable
    
  - object1: tablet
    object2: hand
    operation: enable    
    
  - object1: arm
    object2: hand
#    operation: enable
    operation: disable
    
  - object1: sdh_palm_link
    object2: arm_7_link
    operation: disable

  - object1: sdh_palm_link
    object2: arm_6_link
    operation: disable
  
#  - object1: hand
#    object2: arm_5_link
#    operation: disable

