default_robot_padding: 0.0
link_padding:
  - link: tablet
    padding: 0.03
#  - link: sdh_palm_link
#    padding: 0.02
#  - link: sdh_finger_11_link
#    padding: 0.02
#  - link: sdh_finger_12_link
#    padding: 0.02
#  - link: sdh_finger_13_link
#    padding: 0.02
#  - link: sdh_finger_21_link
#    padding: 0.02
#  - link: sdh_finger_22_link
#    padding: 0.02
#  - link: sdh_finger_23_link
#    padding: 0.02
#  - link: sdh_thumb_1_link
#    padding: 0.02
#  - link: sdh_thumb_2_link
#    padding: 0.02
#  - link: sdh_thumb_3_link
#    padding: 0.02

